version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API üçün port
      - "9091:9091"   # Web Console üçün port
    environment:
      MINIO_ROOT_USER: minioadmin     # İstifadəçi adı
      MINIO_ROOT_PASSWORD: minioadmin # Şifrə
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9091"
    restart: no

volumes:
  minio-data: