server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/FileVaultDb

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  url: http://localhost:9000
  presignedUrlExpiry: 5
  default-buckets: event-background, category-icon, sub-category-icon
  chunkSize: 10485760
  access:
    name: "minioadmin"
    secret: "minioadmin"